export const FETCH_AGENDA_START = "FETCH_AGENDA_START";
export const FETCH_AGENDA_SUCCESS = "FETCH_AGENDA_SUCCESS";
export const FETCH_AGENDA_FAIL = "FETCH_AGENDA_FAIL";

export const SET_CAT = "SET_CAT";
